### ISSUE TITLE
Simplify the process of plugin developers to create questions to the users.

### ISSUE THREAD

**Issue by sravankorumilli** [odpf/optimus#265]

**Comment by siddhanta-rath** [comment]
plugin questions can be defined in the YAML file as below:

```
name: bq2bq
questions:
  - name: Project
    prompt: Project ID
    type: input
    help: Destination bigquery project ID
    default: project_id_1

  - name: Table
    prompt: Table ID
    type: input
    help: Destination bigquery table ID
    default: table_id_1

  - name: Dataset
    prompt: Dataset Name
    type: input
    help: Destination bigquery dataset ID
    default: dataset_id_1

  - name: LoadMethod
    prompt: Load method to use on destination
    type: input
    help: |
       APPEND        - Append to existing table
       REPLACE       - Deletes existing partition and insert result of select query
       MERGE         - DML statements, BQ scripts
       REPLACE_MERGE - [Experimental] Advanced replace using merge query
    default: dataset_id_1
  - type: multiselect
    options:
      - LoadMethodAppend
      - LoadMethodReplace
      - LoadMethodMerge
      - LoadMethodReplaceMerge
      - LoadMethodReplaceAll
    subquestions:
      - ifValue: LoadMethodReplaceMerge
        questions:
          - name: PartitionFilter
            prompt: Partition filter expression
            type: input
            help: |
               Where condition over partitioned column used to delete existing partitions
               in destination table. These partitions will be replaced with sql query result.
               Leave empty for optimus to automatically figure this out although it will be 
               faster and cheaper to provide the exact condition.
               for example: DATE(event_timestamp) >= "{{ .DSTART|Date }}" AND DATE(event_timestamp) < "{{ .DEND|Date }}"
            default: partition_filter_1
```
Internally all the plugins can use the below struct to unmarshal it :

```
type QuestionSet struct {
	Name      string     `yaml:"name"`
	Questions []Question `yaml:"questions"`
}

type Question struct {
	Name         string        `yaml:"name,omitempty"`
	Prompt       string        `yaml:"prompt,omitempty"`
	Type         string        `yaml:"type,omitempty"`
	Help         string        `yaml:"help,omitempty"`
	Default      string        `yaml:"default,omitempty"`
	Options      []string      `yaml:"options,omitempty"`
	SubQuestions []SubQuestion `yaml:"subquestions,omitempty"`
}

type SubQuestion struct {
	IfValue   string     `yaml:"ifValue,omitempty"`
	Questions []Question `yaml:"questions,omitempty"`
}
```
The above YAML example is taken from the below plugin repo code: 

https://github.com/odpf/transformers/blob/main/task/bq2bq/main.go#L112
