### ISSUE TITLE
Support Optimus Sensor

### ISSUE THREAD

**Issue by arinda-arif** [odpf/optimus#400]
**Scope**
1. Support for configuring Neighbour Optimus Sensors which will be used for automated dependency resolution.
2. Use the configured Optimus Sensors for manually specifiying external job dependencies.
3. Creation of Optimus Sensors both manual and automated using external task sensors.

**Comment by irainia** [comment]
To allow Optimus to recognize its neighbours (another Optimus deployment), we will add additional fields in `config.yaml` for neighbours configuration. The form of additional fields:

```yaml
...
resource_managers:
- name: gtf
  type: optimus
  description: this config is for ...
  config:
    host: optimus.gtf.golabs.io:80
    headers:
      GOOGLE_SERVICE_ACCOUNT: AbC19938F012
    body: "{key: 1}"
```

**Comment by irainia** [comment]
To allow Optimus to recognize its neighbours (another Optimus deployment), we will add additional fields in `config.yaml` for neighbours configuration. The form of additional fields:

```yaml
...
resource_managers:
- name: gtf
  type: optimus
  description: this config is for ...
  config:
    host: optimus.gtf.golabs.io:80
    headers:
      GOOGLE_SERVICE_ACCOUNT: AbC19938F012
    body: "{key: 1}"
```

cc: @arinda-arif
