### ISSUE TITLE
Implement google sheets external data table type for bigquery datastore

### ISSUE THREAD

**Issue by vianhazman** [odpf/optimus#44]
Enable google sheets externaltables management for BigQuery datastore via Optimus.

User should be able to:
- Create a google sheets external table by specifying sheets URI
- Define schema for the google sheets external table
- Use metadata management feature such as Labels

The implementation should be able to extend other BigQuery supported external data sources for future development.
About BigQuery external tables: https://cloud.google.com/bigquery/docs/external-tables

**Comment by kushsharma** [comment]
@vianhazman this looks like a nice feature to have and I can see you have already opened a PR for it. Can you also provide a sample of YAML specification that it will use?

**Comment by vianhazman** [comment]
Sure, the following specification is specific for Google Sheets source. In the future, we can add more source types such as Google Drive and GCS with a different configuration in the `config` property:

```
name: project.dataset.table
type: external_table
version: 1
spec:
  schema:
  - name: column_name
    type: STRING
  source: 
    type: google_sheets
    uris:
    - https://docs.google.com/spreadsheets/d/spreadsheet_id
    config:
      range: Sheet1!A1:B4
      skip_leading_rows: 1
```
